canonical/argo-operators

- operators/argo-controller/src/charm.py
fixes error where non-string input will cause an exception when instantiating the `status`
> fix: convert CheckFailed msg to string

- charms/argo-controller/src/charm.py
Charmhub has different SHA hashes than when deploying locally. Update version calculation of `argoproj/argoexec` to account for this
> Fix argoexec version calculation

- charms/argo-controller/metadata.yaml
- charms/argo-server/metadata.yaml
This PR addresses https://github.com/canonical/bundle-kubeflow/issues/425 where a PVC is created per operator, adding the `min-juju-version: 2.9.0` element to prevent that PVC creation.
> Add min-juju-version element to prevent excess PVC creation

- charms/argo-controller/tests/integration/test_charm.py
Update of https://github.com/canonical/argo-operators/pull/28 according to latest Observability Team's review: removed the direct relation between prometheus and argo-controller.
> Removed prometheus-app direct relation in test

- charms/argo-controller/test-integration-requirements.txt
- charms/argo-controller/test-requirements.txt
- charms/argo-controller/tests/integration/test_charm.py
Pin python-libjuju to 3.0 and update prometheus_grafana test case.
Also, revert a wrongly pushed commit.
>  fixes to avoid CI issues caused by observability test cases

- charms/argo-controller/metadata.yaml
This vendors all remotely defined serialized-data-interface schemas, embedding them in the respective metadata.yaml(s) rather than storing them as a remote link.  This is to enable offline deployment of the charms, as described in [jira](https://warthogs.atlassian.net/browse/KF-727?atlOrigin=eyJpIjoiN2JjZTdlMGYxNDQ3NDdlYzljZDQxNDQ1MTk0OTdkNTEiLCJwIjoiaiJ9).
> feat: localize SDI schemas

- charms/argo-controller/metadata.yaml
- charms/argo-server/metadata.yaml
These links in the charm's metadata will be rendered in charmhub.io to get access to relevant information/docs.
> docs: add documentation links to metadata.yaml

- charms/argo-controller/requirements-integration.in
Apparently the juju agent 2.9.34 is not compatible with pythonlib-juju 3.1, causing the following error:
`juju.errors.JujuConnectionError: juju server-version 2.9.34 not supported `
To avoid this, we have to pin to a version below 3.1.
> tests: pin python-libjuju<3.1 to avoid unsupported version errors

- charms/argo-controller/metadata.yaml
- charms/argo-server/metadata.yaml
Bump the argo patch version as a candidate fix for [this](https://discourse.charmhub.io/t/upgrade-argo-to-3-3-9-to-support-enhanced-depends/10795) issue.
According to the [Release Notes](https://github.com/argoproj/argo-workflows/releases/tag/v3.3.9):
* [Fixes](https://github.com/argoproj/argo-workflows/blob/master/CHANGELOG.md#v339-2022-08-09) were introduced in 3.3.9
* No apparent breaking changes are introduced
> feat: version bump 3.3.8 -> 3.3.9

- tools/get-images.sh
Repository specific list of images
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/3.3 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.
> feat: updated get images script without branch checkout for track/3.3

- charms/argo-controller/requirements-integration.in
- charms/argo-controller/requirements-integration.txt
- charms/argo-controller/requirements-unit.txt
- charms/argo-controller/requirements.txt
- charms/argo-server/charmcraft.yaml
- charms/argo-server/requirements-unit.txt
- charms/argo-server/requirements.txt
Bump these package versions to avoid the issues described in https://github.com/canonical/bundle-kubeflow/issues/648.
This PR also unpins setuptools and pip in charmcraft.yaml to avoid an issue with versions incompatibilities:
```
:: Running external command ['/root/parts/charm/build/staging-venv/bin/pip3', 'install', '--upgrade', '--no-binary', ':all:', 'pip', 'setuptools', 'wheel', 'setuptools!=62.2.0', 'pip!=22.1']
::    :: ERROR: Double requirement given: setuptools!=62.2.0 (already in setuptools, name='setuptools')
```
> build: bump juju 2.9.44.0, sdi->0.7.0, pyyaml->6.0.1

- charms/argo-controller/config.yaml
The default executor in argo-controller's charm configuration is now deprecated and removed in more recent versions of argo workflows. We should consider changing the default to emissary, which is actually the default in >=3.3
Fixes #117
> fix: change default executor from pns (deprecated) to emissary

- charms/argo-controller/config.yaml
- charms/argo-controller/src/charm.py
Add executor-image field in the charm's config file in order to avoid deducing it based on the tag of the container image.
Closes #115
> argo-controller: Add executor-image to config

- .github/workflows/integrate.yaml
- charms/argo-controller/requirements-integration.in
- charms/argo-controller/requirements-integration.txt
ci: update juju to 3.1 and microk8s to 1.25
> ci: update juju to 3.1 and microk8s to 1.25

- charms/argo-controller/config.yaml
- charms/argo-controller/src/charm.py
Porting of executor image configuration is required to enable it configuration in `track/3.3`
- Ported configuration of executor image configuration.
- Issue: https://github.com/canonical/argo-operators/issues/115
- PR on main: https://github.com/canonical/argo-operators/pull/125
> fix: ported exec image config

- charms/argo-controller/config.yaml
This PR backports #122 from `main` to `track/3.3`. 
Refs #117
> backport(fix): change default executor from pns (deprecated) to emissary (#122)

- tools/get-images.sh
Get script up-to-date with `main` branch. This summarizes changes introduced in PRs #106 and #124 since the final `get-images.sh` script in `main` branch is different from the one currently in `track/3.3` only by this one line.
Closes #136
> backport: Update get-images script according main branch (#106 and #124)

- charms/argo-controller/config.yaml
updates argo-exec rock version in argo-controller's config.yaml
closes https://github.com/canonical/charmed-kubeflow-uats/issues/38 in `track/3.3`
this change should be done in main as well, PR incoming.
> fix: update argo exec rock version

- charms/argo-controller/src/components/pebble_component.py
closes #143, details in the issue.
Run the `kfp-integration` UATs with `tox -e uats -- --filter "kfp-integration"`
instructions on running the UATs in their [readme](https://github.com/canonical/charmed-kubeflow-uats#run-the-tests)
> fix: remove --namespaced from argo-controller entrypoint

- charms/argo-controller/config.yaml
This commit defaults the executor image to argoproj/argoexec:v3.3.10 to bump the version and avoid canonical/charmed-kubeflow-uats#38.
> chore: use argoproj/argoexec:v3.3.10 as default argoexec image

- charms/argo-controller/config.yaml
integrates the `argoexec` rock `v3.3.10` in the `argo-controller` charm published from https://github.com/canonical/argo-workflows-rocks/commit/c88862fa80c469ef44cfb2cd89e501b6dd3f5ebf
> feat: use argoexec rock v3.3.10

- charms/argo-controller/config.yaml
integrates `argoexec` rock in `track/3.3.10`
cherry-picks 3654e8b96c254006cf543e145c76bd15d9d84b72
> feat: use argoexec rock v3.3.10 (#158)

- charms/argo-controller/src/grafana_dashboards/basic.json.tmpl
* Add `ckf` tag to argo-controller's grafana dashboard.
* Fix dashboard panels not working by:
* Replacing unavailable metrics with available ones
* Change 2 minutes instead of 1 in places where rate() is used since
this requires more than one scrape data points.
* Remove rate() from panel that shows total number of log messages.
Part of canonical/bundle-kubeflow#856
Refs canonical/bundle-kubeflow#834
> fix: Fix dashboard panels not working

- charms/argo-controller/src/grafana_dashboards/basic.json.tmpl
Backport the following:
* Add `ckf` tag to argo-controller's grafana dashboard.
* Fix dashboard panels not working by:
* Replacing unavailable metrics with available ones
* Change 2 minutes instead of 1 in places where rate() is used since
this requires more than one scrape data points.
* Remove rate() from panel that shows total number of log messages.
Part of canonical/bundle-kubeflow#856
Refs canonical/bundle-kubeflow#834
> backport(fix): Fix dashboard panels not working from #157

- charms/argo-controller/config.yaml
- charms/argo-controller/metadata.yaml
- charms/argo-controller/src/charm.py
- charms/argo-controller/src/templates/crds.yaml
- charms/argo-controller/src/templates/minio_configmap.yaml.j2
- charms/argo-controller/tests/unit/test_charm.py
This commit bumps the oci-image to bring the 3.4 version, as well as updates to the CRDs to their corresponding versions.
It also removes the `executor` config option as changing the executor is no longer supported in upstream.
Fixes #166
> chore: bump argo-controller 3.3.10 -> 3.4

- .github/workflows/integrate.yaml
Part of canonical/bundle-kubeflow#944
> ci: use juju 3.4/stable instead of 3.5/stable in track 3.3.10

- charms/argo-controller/requirements-integration.txt
Build charmed-kubeflow-chisme for requirements-integration.txt.
Part of https://github.com/canonical/charmed-kubeflow-chisme/issues/104
> build, tests: bump charmed-kubeflow-chisme 0.4.0 -> 0.4.1

- .github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
> ci(upload-charm): use charmcraft from latest/candidate in track/3.4

- .github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
> ci(upload-charm): use charmcraft from latest/candidate in track/3.3.10

- .github/workflows/integrate.yaml
- .gitignore
- charms/argo-controller/terraform/README.md
- charms/argo-controller/terraform/main.tf
- charms/argo-controller/terraform/outputs.tf
- charms/argo-controller/terraform/variables.tf
- charms/argo-controller/terraform/versions.tf
- charms/argo-controller/tox.ini
Adds a terraform module, as designed in [CC006 - Terraform modules organization in the Juju ecosystem](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) spec. The module facilitates the deployment of `argo-controller` charm, using the [Terraform juju provider](https://registry.terraform.io/providers/juju/juju/latest/docs).
Since the spec is not finalized yet, the PR may miss features/decisions that are still under discussion.
* Omitted `units` from variables (inputs). This is because CKF charms have not been designed to function with more than one units.
* ~~`outputs.tf` and `variables.tf` are (and should be) in alphabetical order as per [Terraform style guide](https://developer.hashicorp.com/terraform/language/style#file-names).~~
* ~~outputs …
> feat: Add terraform module

- charms/argo-controller/tests/integration/test_charm.py
backports #209 into `track/3.4`
> fix: deploy minio from latest/edge in integration tests (#209)

- charms/argo-controller/requirements-fmt.txt
- charms/argo-controller/requirements-integration.txt
- charms/argo-controller/requirements-lint.txt
- charms/argo-controller/requirements-unit.txt
- charms/argo-controller/requirements.txt
- charms/argo-controller/tox.ini
- tox.ini
* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
Ref canonical/bundle-kubeflow#1177
> chore: update python dependencies + pin pip

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- charms/argo-controller/charmcraft.yaml
- charms/argo-controller/config.yaml
- charms/argo-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py
- charms/argo-controller/lib/charms/loki_k8s/v1/loki_push_api.py
- charms/argo-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
- charms/argo-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- charms/argo-controller/metadata.yaml
- charms/argo-controller/requirements-fmt.txt
- charms/argo-controller/requirements-integration.txt
- charms/argo-controller/requirements-lint.txt
- charms/argo-controller/requirements-unit.txt
- charms/argo-controller/requirements.txt
- charms/argo-controller/tox.ini
- tox.ini
Backport CI changes and dependency updates in order to ensure argo-controller from 3.4/stable is up-to-date WRT releasing CKF 1.10.
A follow-up PR will be sent to enable running integration tests both in 1.29 and 1.31 since this charm is used both in CKF 1.9 and 1.10.
Ref https://warthogs.atlassian.net/browse/KF-6860.
> backport: CI + dependency updates

- charms/argo-controller/config.yaml
This PR updates the `argo-exec` rock with the version used in CKF 1.10. The rock was published in [this action](https://github.com/canonical/argo-workflows-rocks/actions/runs/13173637809/job/36768837828).
> Update argo-exec rock

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
- charms/argo-controller/tests/integration/test_charm.py
Closes #231
* update GH runners from 20.04 to 24.04
* use setup-python action to setup python 3.8
* edit the integration tests to use `kubectl` instead of `microk8s kubectl` so that elevated permissions are not needed
* removes `sg` no longer needed based on the previous point
> ci: migrate GH runners to ubuntu 24.04

- charms/argo-controller/src/grafana_dashboards/basic.json.tmpl
Closes #242 
Note to reviewer: CI is failing due to https://github.com/canonical/bundle-kubeflow/issues/1258, I opened #254 as a workaround to unblock this PR
Adds the following panels to the argo dashboard:
* Gauge for workflows missing pods
* Timeseries for the rate of total k8s requests with the status code as legend
* Timeseries for the number of new errors over a  5 minute window
Removes irrelevant panels that show green workflows or show measures on symptoms, not causes.
3 New panels added (excluding bottom left one was already there):
Old panels kept:
> feat: add grafana dashboard panels for failure modes

- charms/argo-controller/src/templates/mlpipeline_minio_artifact_secret.yaml.j2
Closes #237 
This PR simply replaces the `stringData` field in the `mlpipeline-minio-artifact` secret to a `data` field. This fixes the double encoding issue described in #237.
Deploy the necessary charms, and write a sample workflow file:
```
juju deploy argo-controller --channel 3.4/stable 
juju trust argo-controller --scope=cluster
juju deploy minio --channel ckf-1.9/stable
juju relate argo-controller minio
cat <<EOF > hello-world-workflow.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
generateName: hello-world-
spec:
entrypoint: hello-world
templates:
- name: hello-world
container:
image: alpine:latest
command: ["echo"]
args: ["Hello, Argo Workflow!"]
EOF
```
Then, apply the workflow to the `kubeflow` namespace:
```
kubectl create -f hello-world-workflow.yaml -n …
```
> Use `data` instead of `stringData` for minio access_key and secret_key
