bundle.yaml, operators/argo-controller/metadata.yaml, operators/argo-controller/requirements.txt, operators/argo-controller/src/charm.py, operators/argo-controller/test/unit/test_charm.py
Updates argo-controller to serialized-data-interface 0.2.0 and renames minio relation to object-storage.
=> Update argo-controller to SDI 0.2.0

.github/workflows/publish-bundle.yaml, .github/workflows/test-microk8s.yaml, operators/argo-controller/requirements.txt
* SDI version to <0.4.0
* charmcraft pinned to 1.0.0
* added wait for storage deployment in microk8s tests to prevent race condition between juju and microk8s' storage provisioner
=> Bump sdi version/pin charmcraft/fix tests

LICENSE, bundle.yaml, operators/argo-controller/charmcraft.yaml, operators/argo-controller/config.yaml, operators/argo-controller/lint-requirements.txt, operators/argo-controller/metadata.yaml, operators/argo-controller/requirements.txt, operators/argo-controller/src/charm.py, operators/argo-controller/test-integration-requirements.txt, operators/argo-controller/test-requirements.txt, operators/argo-controller/tests/integration/test_charm.py, operators/argo-controller/tests/unit/test_charm.py, operators/argo-controller/tox.ini, operators/argo-server/config.yaml, operators/argo-server/metadata.yaml, operators/argo-server/requirements.txt, operators/argo-server/src/charm.py, operators/argo-server/test-requirements.txt, operators/argo-server/test/unit/test_charm.py, operators/argo-server/tox.ini, tox.ini
- Add all status handling through one function
- Add License, headers and checks
=> Update Status Handling and License Headers

charms/argo-controller/config.yaml, charms/argo-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/argo-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, charms/argo-controller/lint-requirements.txt, charms/argo-controller/metadata.yaml, charms/argo-controller/src/charm.py, charms/argo-controller/src/prometheus_alert_rules/tempfile, charms/argo-controller/src/prometheus_alert_rules/unit_unavailable.rule, charms/argo-controller/tests/integration/test_charm.py
Updated the [integration with prometheus and grafana](https://github.com/canonical/argo-operators/pull/27) according to Observability Team's review
=> Updated integration

charms/argo-controller/src/charm.py, charms/argo-controller/src/grafana_dashboards/basic.json.tmpl
Port 9090 is used by the container while the service is port 8080.
=> Move METRICS_PORT to point to container metrics

charms/argo-controller/metadata.yaml, charms/argo-controller/src/charm.py, charms/argo-controller/tests/integration/test_charm.py
=> Renamed grafana relation

charms/argo-controller/files/crds/argoproj.io_workflowtaskresults.yaml, charms/argo-controller/files/crds/argoproj.io_workflowtasksets.yaml, charms/argo-controller/metadata.yaml, charms/argo-controller/src/charm.py, charms/argo-server/metadata.yaml, charms/argo-server/src/charm.py
=> bump workload versions to 3.3.8

.github/workflows/integrate.yaml
=> ci: microk8s version bump 1.21->1.22

tox.ini
git-xargs programmatic pull request
=> fix: replace whitelist_externals with allowlist_externals

.github/workflows/integrate.yaml, .github/workflows/issues_to_jira.yaml, charms/argo-controller/lib/charms/grafana_k8s/v0/grafana_dashboard.py, charms/argo-controller/lib/charms/observability_libs/v0/juju_topology.py, charms/argo-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py, charms/argo-controller/requirements-fmt.txt, charms/argo-controller/requirements-lint.txt, charms/argo-controller/tests/unit/test_charm.py, charms/argo-server/requirements-fmt.txt, charms/argo-server/requirements-lint.txt, charms/argo-server/requirements-unit.txt, charms/argo-server/requirements.txt
The changes this PR is trying to merge should not affect any argo functionality, they are mainly CI changes.
=> backport `main` latest changes into `track/3.3`

charms/argo-server/metadata.yaml, charms/argo-server/src/charm.py
=> chore: bump argo-server 3.3.8 -> 3.3.10

charms/argo-controller/config.yaml, charms/argo-controller/src/charm.py
Previous PR https://github.com/canonical/argo-operators/pull/135 failed to include reference to ROCK.
- Modified config to refernce ROCK instead of upstream image.
=> Fix port config exec image

charms/argo-controller/CONTRIBUTING.md, charms/argo-server/CONTRIBUTING.md
=> Contributing docs

charms/argo-controller/config.yaml
=> fix: set default of kubelet-insecure config to true

charms/argo-controller/lib/charms/loki_k8s/v1/loki_push_api.py, charms/argo-controller/metadata.yaml, charms/argo-controller/requirements-integration.in, charms/argo-controller/requirements-integration.txt, charms/argo-controller/src/charm.py, charms/argo-controller/tests/integration/test_charm.py, charms/argo-controller/tests/unit/test_charm.py
Added logging relation and cos integration tests from chisme.
fixes: #173
This was also manually tests with pre-deployed cos bundle.
```bash
juju consume u1-k8s:cos.loki-logging 
juju relate loki-logging grafana-agent-k8s
```
=> Add logging relation

charms/argo-controller/requirements-integration.txt, charms/argo-controller/requirements-unit.txt, charms/argo-controller/requirements.txt
Part of canonical/bundle-kubeflow#868
=> build: bump ops to latest possible version

charms/argo-controller/config.yaml
Closes canonical/argo-workflows-rocks#23
=> chore: integrate 3.4.16 rock

charms/argo-controller/requirements-unit.txt, charms/argo-controller/requirements.txt
Part of canonical/bundle-kubeflow#883
=> build: bump jinja2 3.1.x -> 3.1.4

charms/argo-controller/requirements-unit.txt, charms/argo-controller/requirements.txt
Part of canonical/bundle-kubeflow#883
=> build: bump jinja2 3.1.x -> 3.1.4 (#189)

charms/argo-controller/terraform/README.md, charms/argo-controller/terraform/variables.tf, charms/argo-controller/terraform/versions.tf
=> terraform: Update for 0.14 juju-provider

.github/workflows/integrate.yaml, charms/argo-controller/terraform/README.md
=> terraform: Update CI + Remove compatibility note from README

.github/workflows/integrate.yaml, .gitignore, charms/argo-controller/terraform/README.md, charms/argo-controller/terraform/main.tf, charms/argo-controller/terraform/outputs.tf, charms/argo-controller/terraform/variables.tf, charms/argo-controller/terraform/versions.tf, charms/argo-controller/tox.ini
=> feat: Backport terraform module

charms/argo-controller/charmcraft.yaml
Ref canonical/bundle-kubeflow#1178
=> build: Enable building rust dependencies

.github/workflows/integrate.yaml, tox.ini
Ref canonical/bundle-kubeflow#1183
=> ci: install tox using pip

charms/argo-controller/terraform/versions.tf
Updating juju provider requirement to >=0.14.0
=> [KF-7255] Update Juju provider

charms/argo-controller/terraform/variables.tf
=> [KF-7268] chore: pin channel to latest/edge

.github/workflows/integrate.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml, charms/argo-controller/tests/integration/test_charm.py
* ci: migrate GH runners to ubuntu 24.04
* use kubectl in place of microk8s kubectl
=> cherry-pick(ci): migrate GH runners to ubuntu 24.04 from #232

charms/argo-controller/tests/integration/test_charm.py
Pin charms-dependencies according to 1.10/stable bundle.
Close https://warthogs.atlassian.net/browse/KF-7233
=> chore(tests): Pin charms-dependencies

.github/workflows/tiobe_scan.yml, charms/argo-controller/tox.ini
Updating with TIOBE scan, including:
* reformatting tox.ini file to be machine-generated and handled
* coverage.xml generation when running unit tests 
* creating tiobe_scan.yaml file
=> [KF-7281] Enabling TIOBE scan

charms/argo-controller/charmcraft.yaml, charms/argo-controller/requirements-unit.in, charms/argo-controller/requirements-unit.txt, charms/argo-controller/requirements.in, charms/argo-controller/requirements.txt
Workaround for https://github.com/canonical/bundle-kubeflow/issues/1258
=> fix(workaround): pin binary-packages to avoid issues with building from source

charms/argo-controller/config.yaml, charms/argo-controller/metadata.yaml
Closes #275 
Integrates the rocks built in https://github.com/canonical/argo-workflows-rocks/pull/44 and https://github.com/canonical/argo-workflows-rocks/pull/45
=> chore: integrate rocks version 3.5.14

charms/argo-controller/terraform/variables.tf
=> chore: update terraform module channel to 3.5/stable
